repo_url: "https://api.github.com/repos/coreruleset/coreruleset"
ip_lists:
  sources:
    - name: "FireHOL Level 1"
      url: "https://iplists.firehol.org/files/firehol_level1.netset"
      format: "netset"
    - name: "Emerging Threats"
      url: "https://rules.emergingthreats.net/blockrules/compromised-ips.txt"
      format: "netset"
    - name: "CI Army List"
      url: "http://cinsscore.com/list/ci-badguys.txt"
      format: "netset"
    - name: "IPsum"
      url: "https://raw.githubusercontent.com/stamparm/ipsum/master/levels/1.txt"
      format: "netset"
    - name: "BlockList.de"
      url: "https://www.blocklist.de/lists/all.txt"
      format: "netset"
    - name: "Blocklist.de - SSH"
      url: "https://www.blocklist.de/lists/ssh.txt"
      format: "netset"
    - name: "Greensnow"
      url: "https://blocklist.greensnow.co/greensnow.txt"
      format: "netset"
    - name: "Spamhaus DROP"
      url: "https://www.spamhaus.org/drop/drop.txt"
      format: "netset"
    - name: "AlienVault IP Reputation"
      url: "https://reputation.alienvault.com/reputation.data"
      format: "netset"
    - name: "BinaryDefense IPs"
      url: "https://www.binarydefense.com/banlist.txt"
      format: "netset"
    - name: "Nozomi Networks Bad IPs"
      url: "https://osint.nozominetworks.com/badips.txt"
      format: "netset"
    - name: "Dragon Research Group"
      url: "https://drg.pt/blocklist.txt"
      format: "netset"
  output_file: "lists/ip_blacklist.txt"

dns_lists:
  sources:
    - name: "uBlockOrigin Badware"
      url: "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt"
    - name: "Phishing Army"
      url: "https://phishing.army/download/phishing_army_blocklist_extended.txt"
  output_file: "lists/dns_blacklist.txt"

owasp_rules:
  sources:
    - name: "OWASP"
      url: "https://raw.githubusercontent.com/coreruleset/coreruleset/v4.0/rules/"  # Added trailing slash
      format: "crs-rule-conf"
  output_file: "rules/owasp_rules.json"

nasxi_rules:
  sources:
    - name: "Nasxi"
      url: "https://raw.githubusercontent.com/nbs-system/naxsi/master/naxsi_config/naxsi_core.rules"
      format: "nasxi"
  output_file: "rules/nasxi_rules.json"

base_rules:
  sources:
    - name: "Base rules"
      url: "https://raw.githubusercontent.com/fabriziosalmi/caddy-waf/refs/heads/main/rules.json"
      format: "caddywaf"
  output_file: "rules/base_rules.json"


