name: Daily Release

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run scripts to generate lists and rules.json
        run: |
          python scripts/ip.py
          python scripts/dns.py
          python scripts/rules.py

      - name: Get current date
        id: get_date
        run: echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_DATE }}
          release_name: ${{ env.RELEASE_DATE }}
          draft: false
          prerelease: false
          body: |
            Daily release of ip_blacklist.txt, dns_blacklist.txt, and aggregated rules.json.

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: lists/ip_blacklist.txt
          asset_name: ip_blacklist.txt
          asset_content_type: text/plain
      - name: Upload Release Assets dns
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: lists/dns_blacklist.txt
          asset_name: dns_blacklist.txt
          asset_content_type: text/plain
      - name: Upload Release Assets rules
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: rules/rules.json
          asset_name: rules.json
          asset_content_type: application/json
